// Application-specific schema (non-auth tables go here)
// Auth tables are defined in auth.schema.ts (generated by Better Auth)

import { pgTable, text, timestamp, uuid, varchar } from 'drizzle-orm/pg-core';
import { relations } from 'drizzle-orm';

// Auth tables
export { user as users } from './auth.schema';

// Conversations table - stores chat sessions
export const conversations = pgTable('conversations', {
	id: uuid('id').primaryKey().defaultRandom(),
	userId: text('user_id').notNull(),
	title: varchar('title', { length: 255 }).default('New Chat'),
	createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
	updatedAt: timestamp('updated_at', { withTimezone: true })
		.defaultNow()
		.notNull()
		.$onUpdate(() => new Date())
});

// Messages table - stores individual chat messages
export const messages = pgTable('messages', {
	id: uuid('id').primaryKey().defaultRandom(),
	conversationId: uuid('conversation_id').notNull(),
	role: varchar('role', { length: 10 }).notNull(), // 'user' or 'assistant'
	content: text('content').notNull(),
	createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull()
});

// Relations
export const conversationsRelations = relations(conversations, ({ many }) => ({
	messages: many(messages)
}));

export const messagesRelations = relations(messages, ({ one }) => ({
	conversation: one(conversations, {
		fields: [messages.conversationId],
		references: [conversations.id]
	})
}));
